# Generated by Django 3.2.9 on 2021-11-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.JSONField(blank=True, default=[]),
        ),
    ]
