# Generated by Django 3.2.9 on 2021-11-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_product_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cloudinary_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
