# Generated by Django 3.2.9 on 2021-11-23 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_auto_20211122_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='user_id',
            new_name='user',
        ),
    ]
