# Generated by Django 3.2.9 on 2021-11-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_storebanner_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebanner',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
